import type { Metadata } from "next";
import { inter, poppins } from "../../styles/fonts";
import "../../styles/main.css";

export const metadata: Metadata = {
  title: "Swiich Office App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
