import type { Metadata } from "next";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import { inter, poppins } from "../../styles/fonts";
import "../../styles/main.css";
import AppProvider from "@/lib/AppProvider";

export const metadata: Metadata = {
  title: "Swiich Office App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    
  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
      <body>
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
